services:
  - type: web
    name: ai-agent-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app_simple:app --bind 0.0.0.0:$PORT --workers 1 --timeout 120
    healthCheckPath: /api/health
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHONPATH
        value: .
      - key: PORT
        generateValue: true